name: Pull Request Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project files
        uses: actions/checkout@v3

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download and install FBXSDK files
        run: |
          # info
          id
          cat /etc/os-release
          uname -a
          ./build_setup.sh

      - name: Build and run tests
        run: |
          ./all_build.sh
