name: Pull Request Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out project files
        uses: actions/checkout@v3

      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Download and install FBXSDK files
        run: |
          # info
          id
          cat /etc/os-release
          uname -a
          ./.github/workflows/build_setup.sh

      - name: Diag
        run: |
          ls -l /usr/share/
          ls -l /usr/share/fbxsdk/
          ls -l /usr/share/fbxsdk/2020.3.4/
          ls -l /usr/share/fbxsdk/2020.3.4/include

      - name: Build and run tests
        run: |
          ./all_build.sh
